# Generated by Django 3.0.8 on 2020-07-23 02:57

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nmmis.utils.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=nmmis.utils.generators.aphnum_random2, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('catg', models.CharField(max_length=100)),
                ('sub_catg', models.CharField(max_length=100)),
                ('building_no', models.CharField(max_length=100, unique=True)),
                ('land_area', models.IntegerField()),
                ('build_area', models.IntegerField()),
                ('build_date', models.DateField()),
                ('floor', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('roof_type', models.CharField(max_length=100)),
                ('road_access', models.BooleanField(default=False)),
                ('elect_access', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places_images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal.Ward')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'building',
                'ordering': ['id'],
            },
        ),
    ]
