# Generated by Django 3.0.8 on 2020-07-17 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0003_auto_20200717_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('male', models.PositiveIntegerField()),
                ('female', models.PositiveIntegerField()),
                ('hindu', models.PositiveIntegerField()),
                ('buddhist', models.PositiveIntegerField()),
                ('muslim', models.PositiveIntegerField()),
                ('other', models.PositiveIntegerField()),
                ('id', models.CharField(default='YbstITmRuoqrm', editable=False, max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('headquarter', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.District')),
            ],
            options={
                'verbose_name': 'Municipal',
                'verbose_name_plural': 'Minicipals',
            },
        ),
    ]
