# Generated by Django 3.0.8 on 2020-07-23 07:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import nmmis.utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=nmmis.utils.generators.aphnum_random, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal.Ward')),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'db_table': 'road',
                'ordering': ['id'],
            },
        ),
    ]
