# Generated by Django 3.0.8 on 2020-07-23 12:35

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nmmis.utils.generators


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0004_auto_20200723_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=nmmis.utils.generators.aphnum_random, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transformer/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal.Ward')),
            ],
            options={
                'verbose_name': 'Transformer',
                'verbose_name_plural': 'Transformers',
                'db_table': 'transformer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Telecom',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=nmmis.utils.generators.aphnum_random, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='telecom/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipal.Ward')),
            ],
            options={
                'verbose_name': 'Telecom',
                'verbose_name_plural': 'Telecoms',
                'db_table': 'telecom',
                'ordering': ['id'],
            },
        ),
    ]
