# Generated by Django 3.0.8 on 2020-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.CharField(default='ptBOaf3unIDi', editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
