# Generated by Django 3.0.8 on 2020-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20200717_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.CharField(default='578LTuN8ks84', editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
