export const ON_ZOOMED = 'ON_ZOOMED';
export const SET_CENTER = 'SET_CENTER';

export const TOGGLE_PLACE = 'TOGGLE_PLACE';
export const TOGGLE_BUILDING = 'TOGGLE_BUILDING';
export const TOGGLE_ROAD = 'TOGGLE_ROAD';
export const TOGGLE_TELECOM = 'TOGGLE_TELECOM';
export const TOGGLE_TRANSFORMER = 'TOGGLE_TRANSFORMER';