# Generated by Django 3.0.8 on 2020-07-17 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import nmmis.utils.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('male', models.PositiveIntegerField()),
                ('female', models.PositiveIntegerField()),
                ('hindu', models.PositiveIntegerField()),
                ('buddhist', models.PositiveIntegerField()),
                ('muslim', models.PositiveIntegerField()),
                ('other', models.PositiveIntegerField()),
                ('id', models.CharField(default=nmmis.utils.generators.aphnum_random1, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('headquarter', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'province',
                'ordering': ['id'],
            },
        ),
    ]
