# Generated by Django 3.0.8 on 2020-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.CharField(default='FG9rPwnky0g', editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
