# Generated by Django 3.0.8 on 2020-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='OZJn1', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
