# Generated by Django 3.0.8 on 2020-07-16 18:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200715_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='0ha26', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
