# Generated by Django 3.0.8 on 2020-07-16 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20200716_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='DhaeQ', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
