# Generated by Django 3.0.8 on 2020-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20200716_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='H9qzE', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
