# Generated by Django 3.0.8 on 2020-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20200717_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='kI8CfP0sqk', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
